wip

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -12,9 +12,19 @@ fi
 
 # install omz
 sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
+ret=$?
+if [ $ret -ne 0 ]; then
+    echo "Failed to install oh-my-zsh"
+    exit $ret
+fi
 
 # install p10k
 git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
+ret=$?
+if [ $ret -ne 0 ]; then
+    echo "Failed to install powerlevel10k"
+    exit $ret
+fi
 
 mkdir -p ~/.config/nvim/
 if [ "$(ls -A ~/.config/nvim/)" ]; then
