NICE

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -10,20 +10,22 @@ if [ $ret -ne 0 ]; then
     exit $ret
 fi
 
+if [ -z "$ZSH" ]; then
 # install omz
-sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
-ret=$?
-if [ $ret -ne 0 ]; then
-    echo "Failed to install oh-my-zsh"
-    exit $ret
-fi
+    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
+    ret=$?
+    if [ $ret -ne 0 ]; then
+        echo "Failed to install oh-my-zsh"
+        exit $ret
+    fi
 
-# install p10k
-git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
-ret=$?
-if [ $ret -ne 0 ]; then
-    echo "Failed to install powerlevel10k"
-    exit $ret
+    # install p10k
+    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
+    ret=$?
+    if [ $ret -ne 0 ]; then
+        echo "Failed to install powerlevel10k"
+        exit $ret
+    fi
 fi
 
 mkdir -p ~/.config/nvim/
@@ -32,3 +34,24 @@ if [ "$(ls -A ~/.config/nvim/)" ]; then
 else
     git clone git@github.com:d-3nnis/dvim.git ~/.config/nvim/
 fi
+
+# Save this file as ~/.config/yadm/bootstrap and make it executable. It will
+# execute all executable files (excluding templates and editor backups) in the
+# ~/.config/yadm/bootstrap.d directory when run.
+
+# Directory to look for bootstrap executables in
+BOOTSTRAP_D="${BASH_SOURCE[0]}.d"
+
+if [[ ! -d "$BOOTSTRAP_D" ]]; then
+    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
+    exit 1
+fi
+
+find -L "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
+    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
+        if ! "$bootstrap"; then
+            echo "Error: bootstrap '$bootstrap' failed" >&2
+            exit 1
+        fi
+    fi
+done
